### ISSUE TITLE
Publish laravel 4 version, before the Laravel 5 updates.

### ISSUE THREAD

**Issue by dukino** [cribbb/cribbb#9]
It would be nice if you could create a version splitting the code between laravel 4 and laravel 5. It would benefit both developers using L4 as the ones migrating to L5.

PS: thank you for publishing this and all your tutorials. Thank you!

Best regards.

**Comment by philipbrown** [comment]
Hmm, as much as I agree that would be a good idea, I wouldn't have the time to do it.

Thank you :heart:
